import React, { useEffect, useState } from 'react';
import { UserProfile, MeetingSpot } from '../types';
import { getMeetingSuggestions, getConversationStarters } from '../services/geminiService';
import { Button } from './Button';

interface MeetingPlannerProps {
  currentUser: UserProfile;
  targetUser: UserProfile;
  onClose: () => void;
}

export const MeetingPlanner: React.FC<MeetingPlannerProps> = ({ currentUser, targetUser, onClose }) => {
  const [loading, setLoading] = useState(true);
  const [spots, setSpots] = useState<MeetingSpot[]>([]);
  const [icebreakers, setIcebreakers] = useState<string[]>([]);

  useEffect(() => {
    const fetchData = async () => {
      setLoading(true);
      
      // Fetch both in parallel
      const [fetchedSpots, fetchedIcebreakers] = await Promise.all([
        getMeetingSuggestions(currentUser.district, currentUser, targetUser),
        getConversationStarters(currentUser, targetUser)
      ]);

      setSpots(fetchedSpots);
      setIcebreakers(fetchedIcebreakers);
      setLoading(false);
    };

    fetchData();
  }, [currentUser, targetUser]);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
      <div className="bg-white rounded-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto shadow-2xl flex flex-col">
        
        {/* Header */}
        <div className="p-6 border-b border-gray-100 bg-berlin-cream sticky top-0 z-10">
          <h2 className="text-2xl font-serif font-bold text-berlin-dark mb-1">
            Plan your meeting
          </h2>
          <p className="text-gray-600">
            Connecting <span className="font-semibold">{currentUser.name}</span> & <span className="font-semibold">{targetUser.name}</span>
          </p>
        </div>

        {/* Content */}
        <div className="p-6 space-y-8">
          
          {loading ? (
            <div className="flex flex-col items-center justify-center py-12 space-y-4">
              <div className="w-12 h-12 border-4 border-berlin-red border-t-transparent rounded-full animate-spin"></div>
              <p className="text-gray-500 animate-pulse">Consulting our AI for safe, public meeting spots...</p>
            </div>
          ) : (
            <>
              {/* Spots Section */}
              <section>
                <h3 className="text-lg font-bold text-berlin-green mb-4 flex items-center gap-2">
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"></path><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"></path></svg>
                  Suggested Public Meeting Spots
                </h3>
                <div className="grid gap-4 md:grid-cols-1">
                  {spots.map((spot, idx) => (
                    <div key={idx} className="border border-stone-200 rounded-lg p-4 hover:border-berlin-green transition-colors bg-stone-50">
                      <div className="flex justify-between items-start">
                        <h4 className="font-bold text-berlin-dark">{spot.title}</h4>
                        {spot.url && (
                          <a href={spot.url} target="_blank" rel="noopener noreferrer" className="text-xs text-berlin-red underline">
                            View Map
                          </a>
                        )}
                      </div>
                      <p className="text-sm text-gray-500 mt-1">{spot.address}</p>
                      <p className="text-sm text-gray-700 mt-2 bg-white p-2 rounded border border-gray-100 italic">
                        "{spot.description}"
                      </p>
                    </div>
                  ))}
                  <p className="text-xs text-gray-400 mt-2 text-center">
                    These recommendations are generated by AI. Always verify the location and safety before meeting.
                  </p>
                </div>
              </section>

              {/* Conversation Starters */}
              <section>
                <h3 className="text-lg font-bold text-berlin-green mb-4 flex items-center gap-2">
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"></path></svg>
                  Ice Breakers (German / English)
                </h3>
                <div className="bg-berlin-cream rounded-lg p-5 border border-stone-200">
                  <ul className="space-y-3">
                    {icebreakers.map((starter, idx) => (
                      <li key={idx} className="flex gap-3">
                        <span className="text-berlin-red font-bold select-none">{idx + 1}.</span>
                        <span className="text-berlin-dark">{starter}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </section>

              <div className="bg-blue-50 p-4 rounded-lg border border-blue-100 flex gap-3 items-start">
                 <svg className="w-6 h-6 text-blue-500 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                 <div className="text-sm text-blue-800">
                    <p className="font-bold mb-1">Safety First</p>
                    <p>BerlinBrücke encourages meetings ONLY in public places like the ones suggested above. Never meet in a private residence for the first time.</p>
                 </div>
              </div>
            </>
          )}

        </div>

        {/* Footer */}
        <div className="p-6 border-t border-gray-100 flex justify-end gap-3 bg-gray-50 rounded-b-2xl">
          <Button variant="ghost" onClick={onClose}>Close</Button>
          {!loading && (
             <Button onClick={() => alert("Invitation sent! (This is a demo)")}>
                Send Invitation
             </Button>
          )}
        </div>

      </div>
    </div>
  );
};
